/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name char(30),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL
);

ALTER TABLE
    animals
ADD
    COLUMN species VARCHAR(50);

CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(50),
    age INT,
    PRIMARY KEY (id)
);

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50),
    PRIMARY KEY (id)
);

-- Removing species column
ALTER TABLE
    animals DROP COLUMN species;

-- First Creating species_id column
ALTER TABLE
    animals
ADD
    COLUMN species_id INT;

-- Then Referencing it as a foreign key
ALTER TABLE
    animals
ADD
    CONSTRAINT fk_species FOREIGN KEY (species_id) REFERENCES species (id);

-- First Creating owner_id column
ALTER TABLE
    animals
ADD
    COLUMN owner_id INT;

-- Then Referencing it as a foreign key
ALTER TABLE
    animals
ADD
    CONSTRAINT fk_owners FOREIGN KEY (owner_id) REFERENCES owners (id);