/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name char(30),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL
);

ALTER TABLE
    animals
ADD
    COLUMN species VARCHAR(50);

CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(50),
    age INT,
    PRIMARY KEY (id)
);